Repository ctc-casa-ios/ios-app, pull requests merged in 2023-05, with the labels that each got.

#35 Feature #33 - Setup state management for handling Authentication
  .gitignore
  App.tsx
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  src/__mocks__/navigationRef.ts
  src/api/__mocks__/auth.ts
  src/api/auth.ts
  src/components/LoginFields.tsx
  src/context/AuthContext.ts
  src/context/__test__/AuthContext.test.tsx
  src/context/createDataContext.tsx
  src/navigationRef.ts
  src/screens/AccountScreen.tsx
  src/screens/CaseContactListScreen.tsx
  src/screens/LoginScreen.tsx
  src/utils/TBD.tsx
  tsconfig.json
  utils/asyncStorageMock.js
  utils/test-utils.js
Labels: auth

#39 add login screen UI
  App.tsx
  output.css
  package-lock.json
  src/assets/casaLogo.png
  src/assets/rfgLogo.png
  src/components/Button.tsx
  src/components/LoginFields.tsx
  src/screens/LoginScreen.tsx
  tailwind.config.js
  test/loginFields.test.tsx
  yarn.lock
Labels: UI

#46 #42 Authentication Flow: Low priority: UI fixes for log in screen. FIX
  App.tsx
  src/screens/LoginScreen.tsx
Labels: UI

#48 configure workflow CI and fix linting errors
  .github/workflows/ci.yml
  App.tsx
  babel.config.js
  jest.config.js
  src/components/Button.tsx
  src/components/LoginFields.tsx
  src/helper/onPressHelper.ts
  src/screens/AccountScreen.tsx
  src/screens/CaseContactCreateScreen.tsx
  src/screens/CaseContactDetailScreen.tsx
  src/screens/CaseContactListScreen.tsx
  src/screens/LoginScreen.tsx
  test/button.test.tsx
  test/loginFields.test.tsx
Labels: devOps
